server:
  port: 0
  shutdown: graceful

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    schema: classpath*:db/sql/schema.sql
    data: classpath*:db/sql/data.sql
    url: "jdbc:postgresql://${DB_HOSTNAME:localhost}:${DB_PORT:5432}/${DB_BASENAME:beerapp2}"
    username: "${DB_PASSWORD:beerapp2}"
    password: "${DB_PASSWORD:beerapp2}"
  cloud:
    config:
      allow-override: true
      override-none: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
