version: '3.1'

services:
  beerapp2-db:
    image: postgres:13.1
    volumes:
      - ./init/:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password
